### ISSUE TITLE
lp_Tweaky looses alpha channel

### ISSUE THREAD

**Issue by PostPollux** [NatronVFX/natron-plugins#39]
I think there's a bug in lp_Tweaky. No matter what the alpha of my input image is, the output alpha is always completely black.

**Comment by CameraRick** [comment]
That shouldn't happen. I'll take a look.

**Comment by CameraRick** [comment]
I fixed it, I set up a shuffle wrong. Looks like it was on purpose but no idea what the motivation was; Tweaky was one of my first PyPlugs when I still had issues with how Shuffle works, maybe it's that

**Comment by PostPollux** [comment]
Wow, that was fast! :)

**Comment by CameraRick** [comment]
I was having a look at the EdgeBlur issue so I had the page open :)

I also noticed that Tweaky is terribly slow even when nothing is changed. I believe that is due to the amount of colourspace changes. I reworked it so everything that isn't used is disabled, that should result in much more speed. I still hope Natron improves on that end, I notice these slowdowns quite alot unfortunately

I'll try to update it properly shortly
