### ISSUE TITLE
Move all the Pyplugs to their own custom folder

### ISSUE THREAD

**Issue by sozap** [NatronVFX/natron-plugins#46]
As discussed with PostPollux the PositionMask Pyplug would fit better in the Keyer category...

Another option is to create a category for tweaking 3D passes , as some Pyplug (Relight , ZCombine,IDKeyer) are not useful outside this scope.  So someone that is only working with video may never use them and may found them distracting in the menu.

If someone as an idea... or let's just move it when we have time...

**Comment by PostPollux** [comment]
Just a thought that I had. I'm not sure if this would make things better or not:
What about having one "Community PyPlugs" or just "Community" category with sub-categories, where all the PyPlugs are located? A bit like GMIC.
This would make it easier to distinguish between Natron built-in tools and those created by the community. For example if you want to build a new PyPlug you probably want to to use built-in natron tools so you don't end up being dependend on other PyPlugs that are not shipped by default with Natron.
Furthermore, the "Filter" category is already pretty overloaded so that I have to scroll to see all the tools. And I guess there will be more plugins for this category in the future.
Another point is that Natron would look more "the same" across different workstations. For example if I use Natron at home without community PyPlugs installed and help a friend in the office whose got them installed, Natron looks almost the same, there is just the difference that there is one additional "community" category. Like it is right now, all the familiar categories suddenly would look different. I think it's not a big deal, but something that can be a bit confusing.

So my idea was maybe something like this:

-> Community
----> CG Passes
----> Generate (or Draw)
----> Filter
----> Keying
----> Relight
----> Transform


As I said, just an idea. that can be discussed.

**Comment by sozap** [comment]
Good point PostPollux,
I've already discussed about this with Olear at the beginning of the repository, and I found better  at that time that Pyplugs blend with Natron, so it's kind of transparent.
But as the repository is growing it's may be better to switch community pyplug to their own directory as you said.

One thing that bother me is that custom directory have all the same icon ( I don't know if that can be changed) so if you've got several custom dir they are hard to distinguish between one or another.

For me the better would have been to have few plugs (openFX + Pyplug) all in the same meaningful dir , but it's not likely to append.

Let's push the discussion a bit further with more people and see what can be the better solution...

**Comment by CameraRick** [comment]
I'd appreciate the approach PostPollux posted, too. I don't see a big use in having the PyPlugs across the whole program; usually I create them with the tab-menu anyway, the only time I do it over the manual is when I have forgotten the name. When I forget the name AND the category, I'll encounter a bad time :)

After all, a PyPlug may not give the same streamlined experience than full nodes, so the "blending" is a bit inappropriate here I think. Also, I could imagine that some might confuse PyPlug with original node, and go to the wrong bugtracker? No idea if that's a "danger"

**Comment by sozap** [comment]
Ok ! Let's see if it's possible to have a custom icon for Pyplugs directory ( I'll make a post in the forum) and how to organise the migration and let's go for it ! There are too much argument for having a custom folder :)

**Comment by sozap** [comment]
Hey, I haven't got any answers for the custom icon, but as the repository is getting many additions the need of a dedicated folder increase as well.
I can edit the Pyplugs to store them in a "Community" folder or we can split the work...
We just need to inform all the team so new pyplugs get to this folder as well.

**Comment by PostPollux** [comment]
Yes, now with over 50 plugins I think it's time to move them into a "Community" category.

So basically it's just editing the "def getGrouping():" in the .py file for each plugin. Am I right? Should be possible in a couple of minutes. Or am I missing something? Do we need to change some folders and other stuff? And, yes, we shouldn't forget to update the "Guidelines for plugins". 

I just had a quick look at the list again. I think category wise most of the plugins could stay where they are right now. Just with "community/" added to the "def getGrouping():" path. 
For the "relight" category I would remove the "draw" and just use "community/relight/" and for PositionMask I still think it could be moved to "keyer"... :)

Are there other ideas or suggestions where to put which plugins?
Otherwise I think we could just go for it, if there are no concerns form other contributors.

**Comment by sozap** [comment]
yes, it's quite simple to do, I'll make the update and if someone see something that can be improved we can iterate a bit around that. I'll make a post in the forum too .

**Comment by sozap** [comment]
Ok that's done, I've moved the gradient pyplug from the Image to the Draw folder , don't hesitate to make some changes if you found something that can be improved

**Comment by sozap** [comment]
I close this one since it's done, feel free to reopen if there is something related to this subject to be done or changed ...
